language: node_js
node_js:
- '11'
matrix:
  fast_finish: true
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn deps
- yarn lint
- yarn test:ci
after_success:
- yarn coveralls
deploy:
  provider: npm
  email: icrosil@gmail.com
  on:
    repo: icrosil/eslint-plugin-you-dont-need-recompose
  api_key:
    secure: IWhEb5eLJGJVW8L8GXLzvmBFZ2CIjamHcA4+YXsNa/I1TTRVLtqXIrMWICY6OD1D3NQ3C60LdlgzyUuaw2SlXNQON1ETRUUnMEGIIV7E9cFMG20BJKJ4w4/7GpY/6rs14DfMzM00y2Tp9EbwYUw53ITitUxxawz2NeeREzLl3T0bRBQ4XmXck8AE1tj9etOQ6l8mSCDrGqsKMybjc2Cq8sCQI6Wy1o+4W7hfIDEBuU/498RDAnGAOlF1iFwALOkdRfepbR2024Nl6DPrdPqeU0UYRZmmrM12sfamIjCNlq/7QslFJpeuA2B0NrxONF3No54MmdCzXfta+WYofaqvjZpMhHBsCRrcAiz+0BiU5xy6F6YQbneDObsBdNccdIOnwpVQedwG1r0Azb68J2bLpSczs6j63I45KbUZO8gOLs4j+rVrStxcgsJiXQfE98GEeuQZgt1KrIpkib+wIIJyD7bcpmP3BdpKtuq/SbH5LvKEo8buRYYA1QO2AyoT0/Z6o+N5qlm8vjWiyB3Y91C9kY/o1zqfbk9rQV+M6HFF3ZzAOqC8ZDda7R/+dBe8aiKXGMbOGADxtAIqEDhIl0KiXgnytJhbV1SMEN5L4pICktXIN4AKM7UFbj4M/VlPqUsiMYsg+9dS483Xqx1kv1bpUjzyv+SFE7m9nLrDytfJwrA=
notifications:
  email:
    recipients:
    - icrosil@gmail.com
    on_success: change
    on_failure: always
